---
blank_issues_enabled: false
contact_links:
  - name: Solana Stack Exchange
    url: https://github.com/orgs/community/discussions
    about: For questions unrelated to Mobile Wallet Adapter make a post here with the #solana-mobile tag.