name: Expo Smoke Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # Every Monday, 5am UTC
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version: [ 52, 53, 54, latest]

    steps:
      - uses: actions/checkout@v5

      - name: set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true
          cache_dependency_path: 'js/pnpm-lock.yaml'
          package_json_file: 'js/package.json'

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

      - name: 'Build Project'
        working-directory: 'js/'
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: 'Setup Expo App'
        working-directory: 'js/'
        run: |
          if [ "${{ matrix.version }}" = "latest" ]; then
            npx -y create-expo-app expo-${{ matrix.version }}-app --template blank
          else
            npx -y create-expo-app expo-${{ matrix.version }}-app --template blank@sdk-${{ matrix.version }}
          fi

      - name: 'Install mobile-wallet-adapter-protocol'
        working-directory: 'js/'
        run: |
          cd expo-${{ matrix.version }}-app
          npm install file:../packages/mobile-wallet-adapter-protocol

      - name: 'Build Expo App'
        working-directory: 'js/'
        run: |
          npx expo prebuild --no-install
          cd android && ./gradlew assembleDebug --no-daemon --stacktrace

      - name: 'Setup Expo Wallet
        working-directory: 'js/'
        run: |
          if [ "${{ matrix.version }}" = "latest" ]; then
            npx -y create-expo-app expo-${{ matrix.version }}-wallet --template blank
          else
            npx -y create-expo-app expo-${{ matrix.version }}-wallet --template blank@sdk-${{ matrix.version }}
          fi

      - name: 'Install mobile-wallet-adapter-walletlib'
        working-directory: 'js/'
        run: |
          cd expo-${{ matrix.version }}-wallet
          npm install file:../packages/mobile-wallet-adapter-walletlib

      - name: 'Build Expo Wallet'
        working-directory: 'js/'
        run: |
          npx expo prebuild --no-install
          cd android && ./gradlew assembleDebug --no-daemon --stacktrace