name: JavaScript Pre-Publish

on:
  push:
    branches: [ main ]
    paths: [ '.github/**', 'js/**' ]
  pull_request:
    branches: [ main ]
    paths: [ '.github/**', 'js/**' ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: 'js/pnpm-lock.yaml'
      
      - name: Enable Corepack and prepare package manager
        run: |
          corepack enable
          corepack prepare pnpm@10.30.0 --activate

      - name: '[js] Install dependencies'
        working-directory: 'js/'
        run: pnpm install --frozen-lockfile
      # - name: '[js] Lint'
      #   working-directory: 'js/'
      #   run: pnpm lint
        continue-on-error: true # TODO: fix all lint issues and remove this line
      - name: '[js] Build'
        working-directory: 'js/'
        run: pnpm build

      - name: '[mobile-wallet-adapter-protocol] Pre-Publish'
        working-directory: 'js/packages/mobile-wallet-adapter-protocol'
        run: pnpm prepublishOnly

      - name: '[mobile-wallet-adapter-protocol-web3js] Pre-Publish'
        working-directory: 'js/packages/mobile-wallet-adapter-protocol-web3js'
        run: pnpm prepublishOnly

      - name: '[wallet-adapter-mobile] Pre-Publish'
        working-directory: 'js/packages/wallet-adapter-mobile'
        run: pnpm prepublishOnly